# Generated by Django 3.0.6 on 2020-11-18 09:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.TimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('title_1', models.CharField(blank=True, max_length=100, null=True)),
                ('content_1', models.TextField(blank=True, max_length=2000, null=True)),
                ('title_2', models.CharField(blank=True, max_length=100, null=True)),
                ('content_2', models.TextField(blank=True, max_length=2000, null=True)),
                ('title_3', models.CharField(blank=True, max_length=100, null=True)),
                ('content_3', models.TextField(blank=True, max_length=2000, null=True)),
                ('recipients', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
