# Generated by Django 3.0.6 on 2020-11-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='created',
            new_name='stam',
        ),
    ]
