# Generated by Django 3.0.6 on 2020-11-19 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0002_auto_20201119_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='stam',
        ),
    ]
