# Generated by Django 3.0.6 on 2020-11-19 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0003_remove_newsletter_stam'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
