# Generated by Django 3.0.6 on 2020-11-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0004_newsletter_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='button_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='button_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
