# Generated by Django 3.0.6 on 2020-11-23 08:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0005_auto_20201119_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='content_1',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content_2',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='content_3',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
