# Generated by Django 3.0.6 on 2020-11-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0007_auto_20201123_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='recipients_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
