# Generated by Django 3.0.6 on 2020-11-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0008_newsletter_recipients_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='recipients_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
