# Generated by Django 3.0.6 on 2020-11-26 09:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters_app', '0009_newsletter_recipients_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True)),
                ('button_text', models.CharField(blank=True, max_length=20, null=True)),
                ('button_link', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(choices=[('he', 'he'), ('en', 'en')], default='en', max_length=20)),
            ],
        ),
    ]
