# Generated by Django 3.0.7 on 2020-08-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200824_0833'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='business',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_freelancer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_freelancer_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_received',
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='orders.Order'),
        ),
    ]
