# Generated by Django 3.0.7 on 2020-08-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200826_1701'),
        ('payments', '0002_auto_20200828_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='freelancer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Employee'),
            preserve_default=False,
        ),
    ]
