# Generated by Django 3.0.7 on 2020-08-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200826_1701'),
        ('payments', '0004_payment_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='core.Employer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to='core.Employee'),
        ),
    ]
