# Generated by Django 3.0.7 on 2020-08-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200828_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='business',
        ),
    ]
