# Generated by Django 3.0.6 on 2020-06-04 09:01

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200604_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationships',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='relations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000, null=True), size=1), blank=True, null=True, size=1000),
        ),
    ]
