# Generated by Django 3.0.6 on 2020-06-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200604_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='relations',
        ),
    ]
