# Generated by Django 3.0.7 on 2020-06-20 18:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_employee_id_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_doc',
            field=models.FileField(blank=True, null=True, upload_to=core.models.id_path),
        ),
    ]
