# Generated by Django 3.0.7 on 2020-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='credit_card_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
