# Generated by Django 3.0.7 on 2020-08-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
