# Generated by Django 3.0.7 on 2020-06-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200627_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
