# Generated by Django 3.0.7 on 2020-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employer_credit_card_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='freelancer_rating_report',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
