# Generated by Django 3.0.6 on 2020-06-01 20:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=40), default='{stam}', size=1),
            preserve_default=False,
        ),
    ]
