# Generated by Django 3.0.7 on 2020-08-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employer_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='verification_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
