# Generated by Django 3.0.7 on 2020-07-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_freelancer_rating_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='freelancer_rating_report',
        ),
    ]
