# Generated by Django 3.0.7 on 2020-06-29 05:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200627_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='trips',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
