# Generated by Django 3.0.7 on 2020-06-29 05:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employer_trips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='trips',
        ),
        migrations.AddField(
            model_name='employee',
            name='trips',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
