# Generated by Django 3.0.7 on 2020-09-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200830_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
