# Generated by Django 3.0.7 on 2020-07-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employer_credit_card_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='credit_card_info',
        ),
    ]
