# Generated by Django 3.0.7 on 2020-07-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_employer_credit_card_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Phone', 'Phone'), ('PayPal', 'PayPal'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
