# Generated by Django 3.0.7 on 2020-09-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200905_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='business_category',
            field=models.CharField(blank=True, choices=[('Restaurant', 'Restaurant'), ('Clothes', 'Clothes'), ('Convenience', 'Convenience'), ('Grocery', 'Grocery'), ('Office', 'Office'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
