# Generated by Django 3.0.7 on 2020-08-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200724_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_active',
            new_name='is_delivering',
        ),
    ]
