# Generated by Django 3.0.6 on 2020-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200913_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pending',
            field=models.BooleanField(default=False),
        ),
    ]
