# Generated by Django 3.0.7 on 2020-08-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200826_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vehicle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
