# Generated by Django 3.0.6 on 2020-06-04 11:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200604_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationships',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
