# Generated by Django 3.0.6 on 2020-09-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_employee_profile_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_doc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
