# Generated by Django 3.0.6 on 2020-09-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employee_id_doc_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='payment_date',
            new_name='last_payment_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
