# Generated by Django 3.0.7 on 2020-06-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_user_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='new_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='new_messages',
            field=models.IntegerField(default=0),
        ),
    ]
