# Generated by Django 3.0.6 on 2020-09-21 15:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200921_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
