# Generated by Django 3.0.6 on 2020-09-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200921_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
