# Generated by Django 3.0.7 on 2020-06-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200608_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
