# Generated by Django 3.0.6 on 2020-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200924_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payment_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Phone', 'Phone'), ('PayPal', 'PayPal'), ('Other', 'Other')], default='Bank', max_length=50, null=True),
        ),
    ]
