# Generated by Django 3.0.7 on 2020-06-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200609_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Business Profileee', 'verbose_name_plural': 'Business Profiles'},
        ),
    ]
