# Generated by Django 3.0.7 on 2020-06-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200610_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Business Profile', 'verbose_name_plural': 'Business Profiles'},
        ),
        migrations.AddField(
            model_name='employee',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='newsletter_optin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='newsletter_optin',
            field=models.BooleanField(default=True),
        ),
    ]
