# Generated by Django 3.0.6 on 2020-09-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200925_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_level',
            field=models.CharField(choices=[('Rookie', 'Rookie'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Rookie', max_length=30),
        ),
    ]
