# Generated by Django 3.0.7 on 2020-06-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200610_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='b_freelancers',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
