# Generated by Django 3.0.6 on 2020-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200927_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='preferred_payment_method',
            field=models.CharField(choices=[('None', 'None'), ('Bank', 'Bank'), ('Phone', 'Phone'), ('PayPal', 'PayPal'), ('Other', 'Other')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Scooter', 'Scooter'), ('Bicycle', 'Bicycle'), ('Motorcycle', 'Motorcycle'), ('Truck', 'Truck')], max_length=100, null=True),
        ),
    ]
