# Generated by Django 3.0.6 on 2020-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200930_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('1', 'Car'), ('2', 'Scooter'), ('3', 'Bicycle'), ('4', 'Motorcycle'), ('5', 'Truck')], max_length=100, null=True),
        ),
    ]
