# Generated by Django 3.0.7 on 2020-06-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200611_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
