# Generated by Django 3.0.6 on 2020-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200930_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('Car', 'Car'), ('Scooter', 'Scooter'), ('Bicycle', 'Bicycle'), ('Motorcycle', 'Motorcycle'), ('Truck', 'Truck')], max_length=100, null=True),
        ),
    ]
