# Generated by Django 3.0.6 on 2020-11-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200930_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter_optin',
            field=models.BooleanField(default=True),
        ),
    ]
