# Generated by Django 3.0.6 on 2020-11-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201126_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
