# Generated by Django 3.0.6 on 2020-12-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_expired',
            field=models.BooleanField(default=False),
        ),
    ]
