# Generated by Django 3.0.6 on 2020-12-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201215_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_incomplete_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
