# Generated by Django 3.0.7 on 2020-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='language',
            field=models.CharField(choices=[('Hebrew', 'he'), ('English', 'en')], default='en', max_length=20),
        ),
    ]
