# Generated by Django 3.0.7 on 2020-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0002_contentpage_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='language',
            field=models.CharField(choices=[('Hebrew', 'he'), ('English', 'en')], default='English', max_length=20),
        ),
    ]
