# Generated by Django 3.0.7 on 2020-07-06 11:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0002_contentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('content', ckeditor.fields.RichTextField(max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
