# Generated by Django 3.0.6 on 2020-11-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0003_adminparameters_couriers_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminparameters',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
