# Generated by Django 3.0.7 on 2020-07-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
