# Generated by Django 3.0.6 on 2020-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0004_adminparameters_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
