# Generated by Django 3.0.6 on 2020-11-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0005_auto_20201119_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message',
            field=models.BooleanField(default=False),
        ),
    ]
