# Generated by Django 3.0.6 on 2020-11-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0006_adminparameters_alert_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_message_page', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_message_title', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_message_content', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_content',
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_title',
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
