# Generated by Django 3.0.6 on 2020-11-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0007_auto_20201119_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page',
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
