# Generated by Django 3.0.6 on 2020-11-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0009_auto_20201119_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message',
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page_1',
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page_2',
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page_3',
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page_4',
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page_business_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page_business_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page_freelancer_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page_freelancer_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminparameters',
            name='alert_message_page_home',
            field=models.BooleanField(default=False),
        ),
    ]
