# Generated by Django 3.0.6 on 2020-11-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0011_auto_20201125_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmessage',
            name='alert_message_active',
            field=models.BooleanField(default=False),
        ),
    ]
