# Generated by Django 3.0.6 on 2020-11-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0012_alertmessage_alert_message_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page_business_dashboard',
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page_business_signup',
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page_freelancer_dashboard',
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page_freelancer_signup',
        ),
        migrations.RemoveField(
            model_name='adminparameters',
            name='alert_message_page_home',
        ),
    ]
