# Generated by Django 3.0.6 on 2020-12-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0013_auto_20201127_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmessage',
            name='alert_message_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
