# Generated by Django 3.0.6 on 2020-12-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndsos', '0014_alertmessage_alert_message_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmessage',
            name='alert_message_language',
            field=models.CharField(blank=True, default='en', max_length=100, null=True),
        ),
    ]
