-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkzdJLmxbmFanyxxv
sfiPuz0siq15uanKjIm0bSJa+7ugCgYIKoZIzj0DAQehRANCAATYRYvkYETdNTSw
RrxgCfh+JbG2agLlt1FgjHQkteafXJ83L7d21b5X4teECHypueO7dX5ZrybliQwo
/58qj7Fi
-----END PRIVATE KEY-----