# Generated by Django 3.0.7 on 2020-06-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_init_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
