# Generated by Django 3.0.7 on 2020-06-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_userlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='user_id',
            new_name='user',
        ),
    ]
