# Generated by Django 3.0.7 on 2020-06-23 13:39
import os
import json

from django.db import migrations, models
from django.contrib.gis.geos import fromstr
from pathlib import Path
from django.conf import settings

# ISRAELI_DATA_FILENAME = '/Users/alfredshaffir/Documents/proj/dnd_sos/geo/maps/israel/israeli_cities_names.json'
ISRAELI_DATA_FILENAME = os.path.join(settings.BASE_DIR,'geo/maps/israel/israeli_cities_names.json')

def load_data(apps, schema_editor):
    print('loading data...')
    CityModel = apps.get_model('geo', 'CityModel')
    jsonfile = Path(__file__).parents[2] / ISRAELI_DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                city_symbol = obj.get('city_symbol')
                hebrew_name = obj.get('hebrew_name')
                CityModel(city_symbol=city_symbol, hebrew_name = hebrew_name).save()
            except KeyError:
                pass     


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_auto_20200623_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city_symbol', models.CharField(max_length=100)),
                ('hebrew_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'City Models',
                'ordering': ('name',),
            },
        ),

        migrations.RunPython(load_data)

    ]
