# Generated by Django 3.0.7 on 2020-06-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_citymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'verbose_name_plural': 'City Models'},
        ),
    ]
