# Generated by Django 3.0.7 on 2020-06-23 13:39

import json
import os

from django.db import migrations, models
from django.contrib.gis.geos import fromstr
from pathlib import Path
from django.conf import settings

# ISRAELI_STREETS_DATA_FILENAME = '/Users/alfredshaffir/Documents/proj/dnd_sos/geo/maps/israel/israeli_street_and_cities_names.json'
ISRAELI_STREETS_DATA_FILENAME = os.path.join(settings.BASE_DIR,'geo/maps/israel/israeli_street_and_cities_names.json')


def load_data(apps, schema_editor):
    print('loading streets data...')
    Street = apps.get_model('geo', 'Street')
    jsonfile = Path(__file__).parents[2] / ISRAELI_STREETS_DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['streets']:
            try:
                street_id = obj.get('id')
                city_symbol = obj.get('city_symbol')
                city_name = obj.get('city_name')
                street_symbol = obj.get('street_symbol')
                street_name = obj.get('street_name')

                Street(
                    street_id=street_id,
                    city_symbol=city_symbol,
                    city_name=city_name,
                    street_symbol=street_symbol,
                    street_name=street_name).save()
                    
            except KeyError:
                pass     


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_auto_20200623_1359'),
    ]

    operations = [
        migrations.RunPython(load_data)

    ]
