# Generated by Django 3.0.7 on 2020-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_load_streets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='street_id',
            field=models.IntegerField(null=True),
        ),
    ]
