# Generated by Django 3.0.7 on 2020-06-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_auto_20200623_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='street_id',
            field=models.IntegerField(),
        ),
    ]
