# Generated by Django 3.0.7 on 2020-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_auto_20200623_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='country',
            field=models.CharField(default='Israel', max_length=100),
            preserve_default=False,
        ),
    ]
