# Generated by Django 3.0.7 on 2020-07-05 11:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0014_freelancerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
