# Generated by Django 3.0.7 on 2020-06-12 04:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='favorit_freelancers',
        ),
        migrations.AddField(
            model_name='order',
            name='selected_freelancers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000, null=True), size=400), blank=True, null=True, size=1),
        ),
    ]
