# Generated by Django 3.0.7 on 2020-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200716_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
