# Generated by Django 3.0.7 on 2020-07-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_invoice_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='freelancer_rating_report',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
