# Generated by Django 3.0.7 on 2020-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance_to_business',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
