# Generated by Django 3.0.7 on 2020-08-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200823_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
