# Generated by Django 3.0.7 on 2020-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200617_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='order_city_name',
            field=models.CharField(default='fff', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_city_symbol',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_street_name',
            field=models.CharField(default='2ww', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_street_symbol',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
