# Generated by Django 3.0.7 on 2020-06-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200624_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_city_name',
            new_name='city',
        ),
    ]
