# Generated by Django 3.0.7 on 2020-07-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Documents', 'Documents'), ('Clothes', 'Clothes'), ('Tools', 'Tools'), ('Other', 'Other')], default='Food', max_length=50),
        ),
    ]
