# Generated by Django 3.0.6 on 2020-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='business_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
