# Generated by Django 3.0.6 on 2020-05-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200527_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('STARTED', 'STARTED'), ('F_CANCELED', 'F_CANCELED'), ('B_CANCELED', 'B_CANCELED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('SETTLED', 'SETTLED'), ('ARCHIVED', 'ARCHIVED')], default='REQUESTED', max_length=20),
        ),
    ]
