# Generated by Django 3.0.6 on 2020-11-09 06:49

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_order_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_public_id',
            field=models.CharField(default=orders.models.random_string, editable=False, max_length=5),
        ),
    ]
