# Generated by Django 3.0.6 on 2020-11-09 06:55

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_order_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_public_id',
            field=models.CharField(blank=True, default=orders.models.random_string, max_length=5, null=True),
        ),
    ]
