# Generated by Django 3.0.6 on 2020-06-03 06:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200601_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_freelancers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000, null=True), size=400), default='{stam}', size=1),
            preserve_default=False,
        ),
    ]
