# Generated by Django 3.0.6 on 2020-11-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20201109_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_public_id',
        ),
    ]
