# Generated by Django 3.0.6 on 2020-11-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_order_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_public_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
