# Generated by Django 3.0.7 on 2020-06-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200607_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='new_message',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
