# Generated by Django 3.0.7 on 2020-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200607_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='new_message',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
