# Generated by Django 3.0.7 on 2020-06-08 04:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200608_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='new_message',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
